### ISSUE TITLE
windows binary?

### ISSUE THREAD

**Issue by rgl** [infonova/prometheusbeat#15]
Can you please provide an Windows amd64 binary?

**Comment by rgl** [comment]
I was able to create the windows binary with (still need to test it thou...):

```bash
export GOPATH=~/go
mkdir -p $GOPATH/src/github.com/infonova
cd $GOPATH/src/github.com/infonova
git clone https://github.com/infonova/prometheusbeat.git
cd prometheusbeat
export GOX_OS=windows
export GOX_FLAGS='-arch amd64'
make crosscompile
file build/bin/prometheusbeat-windows-amd64.exe
```

**Comment by rgl** [comment]
I was able to create (and test) the windows binary at https://github.com/rgl/prometheusbeat/releases/tag/v6.4.1-windows

**Comment by boernd** [comment]
`make release` should also do the trick (needs docker, plus I have no clue if this works on windows) and build the binaries for all platforms under `build/distributions`. I have added all windows binaries to the latest release.

**Comment by rgl** [comment]
I'm now using the official binaries at https://github.com/rgl/prometheus-vagrant. Thank You!

BTW, didn't you commit anything to this repo to make this happen?

**Comment by boernd** [comment]
> 
> I'm now using the official binaries at https://github.com/rgl/prometheus-vagrant. Thank You!

Nice, you have been starred ;)

> 
> BTW, didn't you commit anything to this repo to make this happen?

No, just attached the release binaries to the github release. If that is what you mean?
