### ISSUE TITLE
Failed to encode event: unsupported float value: -Inf

### ISSUE THREAD

**Issue by shiranp** [infonova/prometheusbeat#19]
Hi, I'm running prometheus 2.5 inside K8s and prometheusbeat on a different host behind nginx,
It seems prometheusbeat can't write metrics to elasticsearch, It keeps repeating the following error:

        ERROR   elasticsearch/client.go:374     Failed to encode event: unsupported float value: -Inf

**Comment by boernd** [comment]
Hi, I added a check for infinity numbers, see PR #20 

Can you test with the docker image infonova/prometheusbeat:infinity if the error goes away?
