### ISSUE TITLE
the data didn't have time

### ISSUE THREAD

**Issue by DORcode** [infonova/prometheusbeat#30]
{
  "_index": "prometheusbeat-7.3.1-2019.09.10",
  "_type": "doc",
  "_id": "UcjkGG0Bq4bH-F3rF0q1",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-09-10T01:39:28.491Z",
    "ecs": {
      "version": "1.0.1"
    },
    "host": {
      "os": {
        "platform": "debian",
        "version": "9 (stretch)",
        "family": "debian",
        "name": "Debian GNU/Linux",
        "kernel": "5.0.7-1.el7.elrepo.x86_64",
        "codename": "stretch"
      },
      "id": "689cfabc30776e6bfe2e7477e81eaa6d",
      "containerized": false,
      "hostname": "prometheusbeat-b4d994dd-d89xb",
      "architecture": "x86_64",
      "name": "prometheusbeat-b4d994dd-d89xb"
    },
    "agent": {
      "version": "7.3.1",
      "type": "prometheusbeat",
      "ephemeral_id": "063b8cbb-45ef-49f7-bb9b-7af21ebdf94d",
      "hostname": "prometheusbeat-b4d994dd-d89xb",
      "id": "3b0510d4-100d-433d-a77b-15cad1ccc940"
    },
    "name": "node_cpu_seconds_total",
    "value": 0,
    "labels": {
      "cpu": "6",
      "endpoint": "https",
      "instance": "*****:9100",
      "namespace": "monitoring",
      "service": "node-exporter-outk8s",
      "job": "node-exporter-outk8s",
      "mode": "steal",
      "prometheus": "monitoring/k8s",
      "prometheus_replica": "prometheus-k8s-0"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-09-10T01:39:28.491Z"
    ]
  },
  "sort": [
    1568079568491
  ]
}

the data prometheusbeat remote write into es ,didn't hava the time,is the doc normal?

**Comment by boernd** [comment]
I'm not sure I can follow. The `@timestamp` field should be mapped as date in the Elasticsearch index. Is this not the case? Do you have an index template in place?
