### ISSUE TITLE
Make error when installing repository

### ISSUE THREAD

**Issue by fedgerth** [infonova/prometheusbeat#33]
Hi, I´m trying to install the prometheusbeat but when I run make setup after downloading repository with git clone, I get this output in the terminal:

~/Desktop/prometheusbeat$ make setup
mkdir -p vendor/github.com/elastic
cp -R /src/github.com/elastic/beats vendor/github.com/elastic/
cp: cannot stat '/src/github.com/elastic/beats': No such file or directory
make: *** [Makefile:28: copy-vendor] Error 1

Am I missing something? Thanks in advance

**Comment by boernd** [comment]
Hi, if you just want to try out prometheusbeat, you can use one of the binaries on the releases page: https://github.com/infonova/prometheusbeat/releases

For locally building the binary you would use the build command: https://github.com/infonova/prometheusbeat#build
